### ISSUE TITLE
Install error:    keybinding.go:74: undefined: termbox.MouseRelease

### ISSUE THREAD

**Issue by Ariels123** [jroimartin/gocui#184] opened 2018-12-20 20:21 UTC
I get this error trying to install on OSx

go get github.com/jroimartin/gocui
# github.com/jroimartin/gocui
../../../../go/src/github.com/jroimartin/gocui/keybinding.go:74: undefined: termbox.MouseRelease

Any easy workaround?

**Comment by whereswaldon** [comment] 2018-12-22 22:56
Never seen this one before. A few questions that might help narrow things down:

- Do you get that error as part of the `go get` command, or when you try to compile some code after having installed?
- What is the output of `go version`?
- What version of macOS are you running?
- What's the output of `pwd` in the directory where you're running this?
- Where is your `$GOPATH`?

**Comment by jroimartin** [comment] 2021-08-14 22:18
Sorry, I cannot reproduce. Also, the issue is quite old, so I'm closing it. If you experience this issue again, feel free to reopen it providing more details.

**Closed by jroimartin** 2021-08-14 22:18 UTC
