### ISSUE TITLE
How do I update a view from another goroutine?

### ISSUE THREAD

**Issue by kgilmer** [jroimartin/gocui#15] opened 2014-02-24 01:58 UTC
I have a top-like application that updates views vi coroutines.  I am able to update the views fine but get panic (panic: bytes.Buffer: truncation out of range) when the terminal is reset.  I notice that if I do not call flush from my update code the error does not occur, but the ui does not refresh until an event is processed.  How do I correctly signal to gocui that a view has changed?

**Comment by c2-akula** [comment] 2015-09-05 00:23
When run this program with the race detector, it detects several data races. Sometime, it even fails to restore the stack, so I tried with "GORACE=history_size=7 go run -race filename.go" and this gives more information and it says that there have been two writes one by the main goroutine and another by the goroutine that does the updating of the views.

**Comment by jroimartin** [comment] 2015-09-05 08:11
I'll give it a look. However, as you can see in the documentation, you must
take care of concurrency when writing/reading to views. They are not
concurrent safe and is the user, depending on his specific case, who must
consider using channels, mutexes, etc.

**Comment by c2-akula** [comment] 2015-09-05 20:09
I am working on a project and as part of it I am using your library for building the UI. I have attached the code that doesn't produce a data-race.
```go
package main

import (
	"fmt"
	"log"
	"math/rand"
	"sync"

	"github.com/jroimartin/gocui"
)

// sview represents a sensor
// in the grid
type sview struct {
	mux *sync.Mutex
	v   *gocui.View
}

type grid struct {
	s []*sview
}

type unfurl struct {
	mux *sync.Mutex
	gui *gocui.Gui
	g   *grid
}

type unfurler interface {
	Init()
}

const (
	// Number of views in our application
	nviews = 25
	// Origin of the views
	vox, voy = 29, 5
	// Size of each view (width x height)
	vsx, vsy = 8, 5
	// Gap between views
	vgap = 1
	// Views are laid as a matrix, and thus
	// dimensions of this matrix
	vrows, vcols = 5, 5
	// The views matrix, is row-oriented and thus
	// the stride is the no.of cols
	voff = vcols
)

// NewUnfurler creates a grid representing the unfurling machine
// with 25 sensor views in the grid each of size, 5 rows by 8 cols.
// Each view is spaced 1 cell apart. The grid's origin is at (29, 5)
func NewUnfurler() unfurler {
	u := new(unfurl)
	u.g = new(grid)
	// 26 views including the title view
	u.g.s = make([]*sview, nviews+1)
	for j := range u.g.s {
		u.g.s[j] = new(sview)
		u.g.s[j].mux = new(sync.Mutex)
		u.g.s[j].v = new(gocui.View)
	}
	u.gui = gocui.NewGui()
	u.mux = new(sync.Mutex)
	return u
}

func (u *unfurl) Init() {
	if err := u.gui.Init(); err != nil {
		log.Panicln(err)
	}
	defer u.gui.Close()

	layout := func(g *gocui.Gui) error {
		var err error
		mx, _ := g.Size()
		// 26th view is our title view for simplicity sake
		u.g.s[nviews].v, err = g.SetView("Title", mx>>1-15, 0, mx>>1+13, 3)
		if err != gocui.ErrorUnkView {
			return err
		}
		fmt.Fprintf(u.g.s[nviews].v, "%s\n%s\n", "Unfurler Data Visualization", "Press Ctrl+C to quit.")
		return nil
	}

	quit := func(g *gocui.Gui, v *gocui.View) error {
		return gocui.Quit
	}

	u.gui.SetLayout(layout)

	// fill gui with the grid
	func(g *gocui.Gui) {
		var err error
		for i := 0; i < vrows; i++ {
			x := vox + i*(vsx+vgap)
			for j := 0; j < vcols; j++ {
				y := voy + j*(vsy+vgap)
				u.g.s[i*voff+j].v, err = g.SetView(string(i*voff+j), x, y, x+vsx, y+vsy)
				if err != gocui.ErrorUnkView {
					log.Panicln(err)
				}
				u.g.s[i*voff+j].v.FgColor = gocui.ColorBlack
				u.g.s[i*voff+j].v.BgColor = gocui.ColorWhite
			}
		}
	}(u.gui)

	// update gui
	// go func() {
	// for {
	for j := 0; j < 10; j++ {
		for i := 0; i < nviews; i++ {
			u.g.s[i].v.Clear()
			fmt.Fprintf(u.g.s[i].v, "%s\n%d\n", "Up", rand.Intn(4096))
			u.gui.Flush()
		}
	}
	// }
	// }()

	if err := u.gui.SetKeybinding("", gocui.KeyCtrlC, gocui.ModNone, quit); err != nil {
		log.Panicln(err)
	}

	if err := u.gui.MainLoop(); err != nil && err != gocui.Quit {
		log.Panicln(err)
	}
}
```
Yes, I am aware this is not idiomatic Go, I cobbled up something to reproduce the situation. As you can see, this code will work just fine if you run it with the race detector. But once you uncomment the go func part of the code, that is when hell breaks loose. The go routines are competing for writing to the same gui and in parts of the error report, it mentions gocui.Flush() method, but commenting that out doesn't solve the datarace problem at all. The application seems to be working fine if you run it without the race detector, but hey, it only takes that one time for it to crash. I suppose that providing a synchronization mechanism as public API could alleviate the problem a bit, by having the user manage the concurrent access to the gui/views. I'd like to know what you think, I am aware that the user will have to deal with low-level routines if the sync mechanism is made public.

**Comment by cruatta** [comment] 2016-01-06 06:36
I'm writing a program myself using this library and I was hoping for a simple example of code that uses goroutines to update a View that doesn't create data races. Any examples would be very much appreciated!

**Comment by jroimartin** [comment] 2016-01-23 15:31
Sorry for my late response. I'll write an example using goroutines and I'll add it under _examples soon. It will be useful also to test race conditions.

**Comment by jroimartin** [comment] 2016-01-25 23:14
gocui is now concurrent-safe via *Gui.Execute() (4b628e45b2697cf5f1734d67401bec21fbce5fee). You have an example on how to update the GUI from goroutines at: https://github.com/jroimartin/gocui/blob/master/_examples/goroutine.go

**Comment by cruatta** [comment] 2016-01-27 09:07
After updating gocui and following your example, my program doesn't have any races that go build -race can detect. Thanks @jroimartin :+1: ! Maybe we can do a new release? This seems like a big milestone to me.

**Comment by jroimartin** [comment] 2016-01-27 10:50
@cruatta yeah, I agree, it makes sense to do a new release. But, before doing it, I want to work a bit more on the documentation and give details about the internals (relations between MainLoop, Keybindings, Execute and Layouts), how to handle concurrency, etc.

I'll release the RC1 during this week.

**Comment by jroimartin** [comment] 2016-01-30 02:09
I've just released [v0.2-rc1](https://github.com/jroimartin/gocui/releases/tag/v0.2-rc1). Please check and give feedback! :)

**Comment by jroimartin** [comment] 2016-01-30 06:54
Also, documentation is a bit more elaborated now :) https://godoc.org/github.com/jroimartin/gocui

**Comment by jroimartin** [comment] 2016-02-07 11:20
I'm closing this issue due to concurrency is already explained on gocui's documentation.

**Closed by jroimartin** 2016-02-07 11:20 UTC
Labels: enhancement
